resolver 127.0.0.11 valid=2s ipv6=off;

upstream backend_pool {
    zone backend_pool 64k;
    server backend:8000 resolve max_fails=1 fail_timeout=5s;
}

server {
    listen 80;

    location / {
        proxy_pass http://backend_pool;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 1s;
        proxy_read_timeout 3s;
        proxy_next_upstream error timeout http_502 http_503 http_504;
        proxy_next_upstream_tries 2;
    }
}
